AudioVariablesClass {
 Variables {
  AudioVariableClass EC29_VonRange {
   source External
   value 1
   value_max 3
  }
  AudioVariableClass EC29_SpectatorListening {
   source External
   value 0
   value_max 1
  }
 }
}