AudioVariablesClass {
 Variables {
  AudioVariableClass EC29_EarRouting {
   source External
   value_max 2
  }
  AudioVariableClass EC29_JamStrength {
   source External
   value 1
  }
  AudioVariableClass EC29_ChannelVolume {
   source External
   value 1
  }
  AudioVariableClass EC29_SignalQuality {
   source External
   value 1
  }
 }
}