SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{684601EE00000302}" : "{A1A24C0D7D3A7EF0}Configs/ConfigurableDialogs/DialogPrefabs/MessageOkCancel.conf" {
   m_sContentLayout "{684601EE00000304}UI/Layouts/Menus/Dialogs/EC29_FrequencyDialogContent.layout"
   m_sTag "ec29_frequency"
   m_sTitle "Set Frequency"
  }
 }
}
