SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{DAE4B75C9D640479}Prefabs/Jammers/EC29_JammerModule_Omni500.et"
  "{5D28BAA97D8B4A1C}Prefabs/Jammers/EC29_JammerModule_Omni1000.et"
  "{F8E6FEB3EDD56EEC}Prefabs/Jammers/EC29_JammerModule_Omni2000.et"
  "{54A26219AA6C9E43}Prefabs/Jammers/EC29_JammerPortable_Omni500.et"
  "{10EAEF91CAE18990}Prefabs/Jammers/EC29_JammerMast_Directional2000.et"
  "{5F8DF577A8DD9544}Prefabs/Jammers/EC29_JammerPortable_Directional500.et"
  "{5A57220A058B8413}Prefabs/Jammers/EC29_JammerMast_Directional1000.et"
 }
}