SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{DAE4B75C9D640479}Prefabs/Editor/EffectsModuleEntities/EC29_JammerOmni500.et"
  "{5D28BAA97D8B4A1C}Prefabs/Editor/EffectsModuleEntities/EC29_JammerOmni1000.et"
  "{F8E6FEB3EDD56EEC}Prefabs/Editor/EffectsModuleEntities/EC29_JammerOmni2000.et"
  "{54A26219AA6C9E43}Prefabs/Jammer500 omnidirectional.et"
  "{10EAEF91CAE18990}Prefabs/Mega_JammerDir2000.et"
  "{5F8DF577A8DD9544}Prefabs/Jammer500 directional.et"
  "{5A57220A058B8413}Prefabs/Mega_JammerDir1000.et"
 }
}