ActionManager {
 Actions {
  Action EC29_VONVoiceRangeCycle {
     InputSource InputSourceSum "{6933A1B7C5E4F001}" {
      Sources {
       InputSourceCombo "{6933A1B7C5E4F002}" {
        FilterPreset "click"
        Sources {
         InputSourceValue "{6933A1B7C5E4F003}" {
          Input "keyboard:KC_F3"
         }
        }
       }
       InputSourceCombo "{6942E72DC16FD02B}" {
        FilterPreset "gamepad:click"
        Sources {
         InputSourceValue "{6942E72DB59ED692}" {
          Input "gamepad0:view"
         }
         InputSourceValue "{6942E72DB2419767}" {
          Input "gamepad0:shoulder_left"
          Filter InputFilterClick "{6942E72D8EFE1EAA}" {
          }
         }
        }
       }
      }
     }
    }
  Action EC29_ToggleEarplugs {
   InputSource InputSourceSum "{612F512ED57FCF8B}" {
    Sources {
     InputSourceValue "{612F512ED38C9CDC}" {
      FilterPreset "toggle"
      Input "keyboard:KC_F2"
      Filter InputFilterClick "{612F512EC90A37DE}" {
      }
     }
     InputSourceCombo "{612F512E9FABA325}" {
      Sources {
       InputSourceValue "{612F512E9C420633}" {
        Input "gamepad0:shoulder_left"
       }
       InputSourceValue "{612F512E71528F7F}" {
        FilterPreset "gamepad:toggle"
        Input "gamepad0:pad_down"
        Filter InputFilterClick "{612F512E6271379C}" {
        }
       }
      }
     }
    }
   }
  }
 }
}
