SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory {
   m_sName "EC29"
   m_sDisplayName "29th ID - Voice Systems"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{61E1242C8D280DC6}
    SCR_KeyBindingEntry "{612F512E24B74E94}
    SCR_KeyBindingEntry "{61E1242C8D280DC6}
    SCR_KeyBindingEntry "{612F512E24B74E93}
   }
  }
 }
}
