SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{01C46AA6F9BAB9A9}" {
   m_sName "EC29"
   m_sDisplayName "#EC29-KeybindCategory_29th"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{86E297AA544A0A69}" {
     m_sActionName "separator"
     m_sDisplayName "#EC29-KeybindSeparator_General"
    }
    SCR_KeyBindingEntry "{9E6B3B30295C49D2}" {
     m_sActionName "EC29_VONVoiceRangeCycle"
     m_sDisplayName "#EC29-Keybind_EC29_VONVoiceRangeCycle"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{9EC2A6A5581AFE6B}" {
     m_sActionName "EC29_ToggleEarplugs"
     m_sDisplayName "#EC29-Keybind_EC29_Earplugs"
     m_sPreset "toggle"
    }
    SCR_KeyBindingEntry "{2C07338530CA4AC7}" {
     m_sActionName "separator"
     m_sDisplayName "Radio"
    }
    SCR_KeyBindingEntry "{24FB88F82110DD4E}" {
     m_sActionName "EC29_SetFrequencyAction"
     m_sDisplayName "Radio: tune frequency"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{C8F845885D4431BA}" {
     m_sActionName "EC29_VONRoutingAction"
     m_sDisplayName "Radio: cycle ear"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{74DF19166C1EF06F}" {
     m_sActionName "EC29_VONBeepTypeAction"
     m_sDisplayName "Radio: cycle PTT tone"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{025FE79719CF6392}" {
     m_sActionName "EC29_VolumeUp"
     m_sDisplayName "Radio: net volume up"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{EA3304D4F51CB6C6}" {
     m_sActionName "EC29_VolumeDown"
     m_sDisplayName "Radio: net volume down"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{A3FD36421EB897D0}" {
     m_sActionName "EC29_AlternateChannelAction"
     m_sDisplayName "Radio: mark second net"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{F34E46E90D99345E}" {
     m_sActionName "EC29_AlternateChannel"
     m_sDisplayName "Radio: talk on second net"
     m_sPreset "hold"
    }
   }
  }
 }
}
