SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{61E1242927F56F6E}" {
   m_sName "EC29"
   m_sDisplayName "#EC29-KeybindCategory_29th"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{61E1242C8D280DC6}" {
     m_sActionName "separator"
     m_sDisplayName "#EC29-KeybindSeparator_General"
    }
    SCR_KeyBindingEntry "{612F512E24B74E94}" {
     m_sActionName "EC29_VONVoiceRangeCycle"
     m_sDisplayName "#EC29-Keybind_EC29_VONVoiceRangeCycle"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{612F512E24B74E93}" {
     m_sActionName "EC29_ToggleEarplugs"
     m_sDisplayName "#EC29-Keybind_EC29_Earplugs"
     m_sPreset "toggle"
    }
    SCR_KeyBindingEntry "{684601EE00000001}" {
     m_sActionName "separator"
     m_sDisplayName "Radio"
    }
    SCR_KeyBindingEntry "{673015ECFF37B6A1}" {
     m_sActionName "EC29_SetFrequencyAction"
     m_sDisplayName "Set Frequency"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{673015ED48240B1B}" {
     m_sActionName "EC29_VONRoutingAction"
     m_sDisplayName "Change Ear Routing"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{673015ED521486CC}" {
     m_sActionName "EC29_VONBeepTypeAction"
     m_sDisplayName "Change Beep Sound"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{673167E9928C3D91}" {
     m_sActionName "EC29_VolumeUp"
     m_sDisplayName "Channel Volume Up"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{684601EE00000405}" {
     m_sActionName "EC29_VolumeDown"
     m_sDisplayName "Channel Volume Down"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{67451A0100000010}" {
     m_sActionName "EC29_AlternateChannelAction"
     m_sDisplayName "Set Alternate Channel"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{67451A0100000020}" {
     m_sActionName "EC29_AlternateChannel"
     m_sDisplayName "Transmit Alternate"
     m_sPreset "hold"
    }
   }
  }
 }
}
