SCR_AvailableActionsDisplay : "{80CC0413DDBDFCB9}Configs/ControlHints/AvailableActions.conf" {
 m_aActions {
  SCR_AvailableActionContext "{08B1D9968C74C86A}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{4E52072A98A0563D}" {
    }
   }
   m_sTag "EC29_VON"
   m_sAction "EC29_SetFrequencyAction"
   m_sName "Tune Frequency"
  }
  SCR_AvailableActionContext "{F5CAAF3162C08C09}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{AEEA2B74B25FB697}" {
    }
   }
   m_sTag "EC29_VON"
   m_sAction "EC29_VONRoutingAction"
   m_sName "Cycle Ear (L/R/Both)"
  }
  SCR_AvailableActionContext "{5E297C425F10A0BF}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{6FE8A206CFB5CE9D}" {
    }
   }
   m_sTag "EC29_VON"
   m_sAction "EC29_VONBeepTypeAction"
   m_sName "Cycle PTT Tone"
  }
  SCR_AvailableActionContext "{4C299C5F1AFFEFE7}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{847CACA911D6E872}" {
    }
   }
   m_sTag "EC29_VON"
   m_sAction "EC29_VolumeUp"
   m_sName "Net Volume"
  }
  SCR_AvailableActionContext "{F31705E1FA06828F}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{C60D5DE01D0C3A29}" {
    }
   }
   m_sTag "EC29_VON"
   m_sAction "EC29_AlternateChannelAction"
   m_sName "Mark Second Net"
  }
  SCR_AvailableActionContext "{00A8B60A5E0CE9F1}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{04D16021DB2C3695}" {
    }
   }
   m_sTag "EC29_VON"
   m_sAction "EC29_AlternateChannel"
   m_sName "Talk on Second Net"
  }
 }
}